name: cnet_store_customer
description: C-Net Store customer application.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  flutter_secure_storage: ^9.2.4
  go_router: ^16.0.0
  cached_network_image: ^3.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
