@extends('layouts.storefront')
@section('content')
<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Bihar Sharif's local marketplace</span><h1>Everything you need,<br><em>delivered locally.</em></h1><p>Shop trusted local stores, order daily groceries and enjoy restaurant food—all in one C-Net Store.</p><div class="hero-buttons"><a class="btn primary" href="{{ route('catalog') }}">Start Shopping</a><a class="btn secondary" href="{{ route('catalog', ['type' => 'food']) }}">Order Food</a></div><div class="trust"><span>✓ Online payments</span><span>✓ Trusted sellers</span><span>✓ Local delivery</span></div></div><div class="hero-art"><img src="{{ asset('images/cnet-store-logo.png') }}" alt="C-Net Store"><div class="floating one">🛍️ Shopping</div><div class="floating two">🥬 Grocery</div><div class="floating three">🍛 Food</div></div></div></section>

<section class="container services"><a class="service blue" href="{{ route('catalog', ['type' => 'shopping']) }}"><span>🛍️</span><div><h2>Shopping</h2><p>Products from local stores</p></div><b>→</b></a><a class="service green" href="{{ route('catalog', ['type' => 'grocery']) }}"><span>🥦</span><div><h2>Grocery</h2><p>Fresh daily essentials</p></div><b>→</b></a><a class="service orange" href="{{ route('catalog', ['type' => 'food']) }}"><span>🍽️</span><div><h2>Food Delivery</h2><p>Restaurants near you</p></div><b>→</b></a></section>

@if($banners->isNotEmpty())<section id="offers" class="section container"><div class="section-head"><div><span>Limited time</span><h2>Top Offers</h2></div></div><div class="offer-row">@foreach($banners as $banner)<article class="offer"><div><small>{{ $banner->subtitle }}</small><h3>{{ $banner->title }}</h3><a href="{{ $banner->target_type === 'url' ? $banner->target_value : route('catalog') }}">Shop now →</a></div></article>@endforeach</div></section>@endif

<section class="section container"><div class="section-head"><div><span>Browse easily</span><h2>Popular Categories</h2></div><a href="{{ route('catalog') }}">View all →</a></div><div class="category-grid">@forelse($categories as $category)<a href="{{ route('catalog', ['category' => $category->slug]) }}"><div class="category-icon">{{ match($category->marketplace) {'food' => '🍲','grocery' => '🥕',default => '🛒'} }}</div><strong>{{ $category->name }}</strong></a>@empty @foreach(['Electronics','Fashion','Grocery','Restaurants','Home & Kitchen','Beauty'] as $name)<a href="{{ route('catalog', ['q' => $name]) }}"><div class="category-icon">🛒</div><strong>{{ $name }}</strong></a>@endforeach @endforelse</div></section>

<section class="section container"><div class="section-head"><div><span>Near you</span><h2>Local Stores & Restaurants</h2></div><a href="{{ route('catalog') }}">Explore all →</a></div><div class="store-grid">@forelse($businesses as $business)<a class="store-card" href="{{ route('businesses.show', $business) }}"><div class="store-cover">{{ match($business->type->value ?? $business->type) {'restaurant' => '🍛','grocery' => '🥬',default => '🏪'} }}</div><div class="store-body"><h3>{{ $business->name }}</h3><p>{{ ucfirst(str_replace('_',' ', $business->type->value ?? $business->type)) }} • Bihar Sharif</p><span>View store →</span></div></a>@empty <div class="empty">Approved local stores will appear here.</div>@endforelse</div></section>

<section class="section container"><div class="section-head"><div><span>Recommended</span><h2>Popular Products</h2></div><a href="{{ route('catalog') }}">View all →</a></div><div class="product-grid">@forelse($products as $product) @include('storefront.partials.product-card', ['product' => $product]) @empty <div class="empty">Products will appear after seller approval.</div>@endforelse</div></section>

<section class="app-promo"><div class="container"><div><span class="eyebrow">Coming on Android & iOS</span><h2>C-Net Store in your pocket</h2><p>Faster ordering, live delivery updates and exclusive app offers.</p></div><img src="{{ asset('images/cnet-store-logo.png') }}" alt="C-Net Store App"></div></section>
@endsection

